# Generated by Django 4.0 on 2023-05-19 00:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0001_initial'),
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_hub', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('passcode', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete')], max_length=200)),
                ('cohorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.cohorts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('screen_short', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('task_img', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField()),
                ('task_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('my_assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.assigment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('ending_date', models.DateTimeField(auto_created=True)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active')], max_length=200)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('cohorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.cohorts')),
            ],
        ),
    ]
