# Generated by Django 4.0 on 2023-05-04 11:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_created=True)),
                ('project_name', models.CharField(max_length=200)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.payment')),
            ],
        ),
    ]
