# Generated by Django 4.0 on 2023-05-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('dash', '0008_alter_payment_date'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('git_hub', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete')], default='reviewing', max_length=200)),
                ('cohorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.cohorts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('my_assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.assigment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
    ]
