# Generated by Django 4.0 on 2023-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('pending', 'pending')], default='pending', max_length=200),
        ),
    ]
