# Generated by Django 4.0 on 2023-05-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_assigment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='project',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete')], max_length=200),
        ),
    ]
