# Generated by Django 4.0 on 2023-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_cohorts_alter_project_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ending_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
