# Generated by Django 4.0 on 2023-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_assigment_project_alter_assigment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='passcode',
            field=models.CharField(default=2, max_length=200),
        ),
    ]
