# Generated by Django 4.0 on 2023-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_end_date_project_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ending_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_created=True),
        ),
    ]
