# Generated by Django 4.0 on 2023-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_assigment_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='passcode',
            field=models.CharField(max_length=200),
        ),
    ]
