# Generated by Django 4.0 on 2023-10-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_assigment_score_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='score_project',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
