# Generated by Django 4.0 on 2023-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_ending_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('active', 'active')], default='yes', max_length=200),
        ),
    ]
