# Generated by Django 4.0 on 2023-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_assigment_score_project_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete')], default='reviewing', max_length=200),
        ),
    ]
