# Generated by Django 4.0 on 2025-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_assigment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('reviewing', 'reviewing'), ('complete', 'complete'), ('reject', 'reject')], default='reviewing', max_length=200),
        ),
    ]
