# Generated by Django 4.0 on 2023-05-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('projects', '0008_alter_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('task_img', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField()),
                ('task_description', models.TextField(max_length=2000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Task_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=200)),
                ('screen_short', models.ImageField(upload_to='taskimage')),
                ('links', models.URLField(blank=True)),
                ('links2', models.URLField(blank=True)),
                ('links3', models.URLField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.myuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.task')),
            ],
        ),
    ]
