# Generated by Django 4.0 on 2023-05-15 16:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_task_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
