# Generated by Django 4.0 on 2023-05-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_task_collections_links2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_collections',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
