# Generated by Django 4.0 on 2023-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
