# Generated by Django 4.0 on 2023-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='images',
            field=models.ImageField(upload_to='coursesimage'),
        ),
    ]
