# Generated by Django 4.0 on 2023-05-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profiles_cohorts_alter_profiles_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='social',
        ),
        migrations.AddField(
            model_name='profiles',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='git_hub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
