# Generated by Django 4.0 on 2023-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='passcode',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
