# Generated by Django 4.0 on 2023-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_payment_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('reject', 'reject')], default='approved', max_length=200),
        ),
    ]
