# Generated by Django 4.0 on 2023-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='passcode',
            field=models.CharField(max_length=20),
        ),
    ]
