# Generated by Django 4.0 on 2023-05-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recapcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recapsesion',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cohorts.recapcourse'),
        ),
    ]
